version: '3.5'

services:
  api:
    container_name: 'snippet-runner-app'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME=${USERNAME}
        - TOKEN=${TOKEN}
    ports:
      - '8082:8082'
